apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "chart.fullname" . }}-kafka
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "chart.fullname" . }}
  pollingInterval:  30
  cooldownPeriod:   300
  minReplicaCount:  1
  maxReplicaCount:  15
  fallback:
    failureThreshold: 3
    replicas: 2
  triggers:
  - type: kafka
    metadata:
      bootstrapServersFromEnv: KAFKA_BROKERS
      consumerGroupFromEnv: KAFKA_GROUPID
      topicFromEnv: KAFKA_TOPIC
      lagThreshold: '5'
      offsetResetPolicy: latest
      allowIdleConsumers: 'false'
      sasl: plaintext
    authenticationRef: 
      name: "{{ include "chart.fullname" . }}-kafka-credentials"
