# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: yosefrow/scalable-shop-cm-server
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: "scalable-shop-cm-server"

securityContext:
  runAsNonRoot: true

service:
  type: NodePort
  nodePort: 30031
  port: 3001

resources:
  requests:
    cpu: "0.5"
    memory: "250M"
  limits:
    cpu: "1"
    memory: "500M"

startupProbe:
  httpGet:
    path: /healthz
    port: 3001
  failureThreshold: 30
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /healthz
    port: 3001
  failureThreshold: 1
  periodSeconds: 35
livenessProbe:
  httpGet:
    path: /healthz
    port: 3001
  failureThreshold: 5
  periodSeconds: 30

kafka:
  username: user1
  password: my-pass
  brokers: kafka-controller-0.kafka-controller-headless.kafka:9092
cmApi:
  host: scalable-shop-cm-api:3000

# The app expects to receive naked paths like /healthz
# So ingress implementations should respect that 
# ${FULL_NAME} is replaced with the name of the service
# e.g. scalable-shop-cm-server
ingress:
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: localhost
      paths:
        - path: /${FULL_NAME}(/|$)(.*)
          pathType: ImplementationSpecific